# Generated by Django 5.2.8 on 2025-11-23 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_course_code_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程', 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '修課紀錄', 'verbose_name_plural': '修課紀錄'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '學生', 'verbose_name_plural': '學生'},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='課程代碼'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='課程名稱'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=20, verbose_name='授課教師'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='期末考分數'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm_score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='期中考分數'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student', verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
