# Generated by Django 6.0 on 2025-12-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
