# Generated by Django 5.2.9 on 2025-12-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.teacheraccount'),
        ),
    ]
